// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_profanity_summary.sql

package db

import (
	"context"
)

const getProfanitySummary = `-- name: GetProfanitySummary :one
WITH filtered_sessions AS (
  SELECT harness, filename, start_time, end_time, duration_sec, project, cwd, models, cost, in_tok, out_tok, cache_tok, user_turns, agent_turns, errors, tool_count, tool_error_count, tool_breakdown, tool_error_breakdown, model_tool_breakdown, model_stats
  FROM t_sessions s
  WHERE ($1::int = 0 OR epoch_ms(s.start_time) >= current_date - to_days($1::int))
    AND ($2::text = '' OR s.project = $2)
    AND ($3::text = '' OR s.filename = $3)
    AND ($4::text = '' OR s.harness = $4)
    AND ($5::text = '' OR EXISTS (SELECT 1 FROM t_session_model_stats_raw sms WHERE sms.harness = s.harness AND sms.filename = s.filename AND sms.provider = $5))
    AND ($6::text = '' OR EXISTS (SELECT 1 FROM t_session_model_stats_raw sms WHERE sms.harness = s.harness AND sms.filename = s.filename AND sms.model = $6))
    AND ($7::text = '' OR EXISTS (SELECT 1 FROM t_model_tools mt WHERE mt.harness = s.harness AND mt.filename = s.filename AND mt.tool = $7))
),
filtered_hits AS (
  SELECT h.hit_id, h.harness, h.filename, h.project, h.ts, h.word, h.group_name, h.severity, h.model, h.provider
  FROM t_profanity_hits_attributed h
  JOIN filtered_sessions s ON s.harness = h.harness AND s.filename = h.filename
  WHERE ($5::text = '' OR h.provider = $5)
    AND ($6::text = '' OR h.model = $6)
),
agg AS (
  SELECT
    (SELECT COUNT(*) FROM filtered_hits)::bigint as total_swears,
    (SELECT COUNT(*) FROM filtered_hits WHERE severity = 'strong')::bigint as strong_swears,
    (SELECT COUNT(DISTINCT harness || ':' || filename) FROM filtered_hits)::bigint as sessions_with_swears,
    (SELECT COUNT(*) FROM filtered_sessions)::bigint as sessions,
    COALESCE((SELECT SUM(user_turns) FROM filtered_sessions), 0)::bigint as user_turns,
    COALESCE((SELECT group_name FROM filtered_hits GROUP BY group_name ORDER BY COUNT(*) DESC, group_name LIMIT 1), '')::text as top_group
)
SELECT
  total_swears,
  strong_swears,
  sessions_with_swears,
  sessions,
  user_turns,
  top_group,
  CASE WHEN user_turns = 0 THEN '0.00' ELSE printf('%.2f', total_swears * 1.0 / user_turns) END::text as swears_per_user_turn_display,
  CASE WHEN sessions = 0 THEN '0.00' ELSE printf('%.2f', total_swears * 1.0 / sessions) END::text as swears_per_session_display,
  CASE WHEN sessions = 0 THEN '0%' ELSE printf('%.1f%%', sessions_with_swears * 100.0 / sessions) END::text as sessions_with_swears_pct
FROM agg
`

type GetProfanitySummaryParams struct {
	Days     int32
	Project  string
	Filename string
	Harness  string
	Provider string
	Model    string
	Tool     string
}

type GetProfanitySummaryRow struct {
	TotalSwears              int64
	StrongSwears             int64
	SessionsWithSwears       int64
	Sessions                 int64
	UserTurns                int64
	TopGroup                 string
	SwearsPerUserTurnDisplay string
	SwearsPerSessionDisplay  string
	SessionsWithSwearsPct    string
}

func (q *Queries) GetProfanitySummary(ctx context.Context, arg GetProfanitySummaryParams) (GetProfanitySummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getProfanitySummary,
		arg.Days,
		arg.Project,
		arg.Filename,
		arg.Harness,
		arg.Provider,
		arg.Model,
		arg.Tool,
	)
	var i GetProfanitySummaryRow
	err := row.Scan(
		&i.TotalSwears,
		&i.StrongSwears,
		&i.SessionsWithSwears,
		&i.Sessions,
		&i.UserTurns,
		&i.TopGroup,
		&i.SwearsPerUserTurnDisplay,
		&i.SwearsPerSessionDisplay,
		&i.SessionsWithSwearsPct,
	)
	return i, err
}
