// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_summary.sql

package db

import (
	"context"
)

const getSummary = `-- name: GetSummary :one
WITH filtered AS (
  SELECT harness, filename, start_time, end_time, duration_sec, project, cwd, models, cost, in_tok, out_tok, cache_tok, user_turns, agent_turns, errors, tool_count, tool_error_count, tool_breakdown, tool_error_breakdown, model_tool_breakdown, model_stats
  FROM t_sessions s
  WHERE ($1::int = 0 OR epoch_ms(start_time) >= current_date - to_days($1::int))
    AND ($2::text = '' OR project = $2)
    AND ($3::text = '' OR filename = $3)
    AND ($4::text = '' OR EXISTS (SELECT 1 FROM t_unified_events e WHERE e.harness = $4 AND e.harness = s.harness AND e.filename = s.filename))
    AND ($5::text = '' OR EXISTS (SELECT 1 FROM t_session_model_stats_raw sms WHERE sms.harness = s.harness AND sms.filename = s.filename AND sms.provider = $5))
    AND ($6::text = '' OR EXISTS (SELECT 1 FROM t_session_model_stats_raw sms WHERE sms.harness = s.harness AND sms.filename = s.filename AND sms.model = $6))
    AND ($7::text = '' OR EXISTS (SELECT 1 FROM t_unified_events e WHERE e.harness = s.harness AND e.filename = s.filename AND e.tool = $7))
),
agg AS (
  SELECT
    COALESCE(SUM(cost), 0)::float8 as total_spend,
    COALESCE(SUM(in_tok + out_tok), 0)::bigint as total_tokens,
    COALESCE(SUM(in_tok), 0)::bigint as in_tokens,
    COALESCE(SUM(out_tok), 0)::bigint as out_tokens,
    COALESCE(SUM(cache_tok), 0)::bigint as cache_tokens,
    COUNT(DISTINCT filename)::bigint as sessions,
    CAST(COALESCE(AVG(CASE WHEN duration_sec > 0 AND duration_sec < 86400 THEN duration_sec END), 0) AS BIGINT) as avg_duration,
    COUNT(CASE WHEN duration_sec > 0 AND duration_sec < 86400 THEN 1 END)::bigint as timed_sessions,
    COALESCE(SUM(tool_count), 0)::bigint as tool_calls,
    COALESCE(SUM(tool_error_count), 0)::bigint as tool_errors,
    COALESCE(SUM(agent_turns), 0)::bigint as agent_turns,
    COALESCE(SUM(user_turns), 0)::bigint as user_turns,
    COUNT(CASE WHEN json_array_length(models) > 1 THEN 1 END)::bigint as multi_model_sessions
  FROM filtered
),
derived AS (
  SELECT total_spend, total_tokens, in_tokens, out_tokens, cache_tokens, sessions, avg_duration, timed_sessions, tool_calls, tool_errors, agent_turns, user_turns, multi_model_sessions,
    (agent_turns + user_turns)::bigint as total_turns,
    CASE WHEN (agent_turns + user_turns) = 0 THEN 0 ELSE CAST(total_tokens / (agent_turns + user_turns) AS BIGINT) END as avg_tokens_per_turn
  FROM agg
)
SELECT
  total_spend,
  total_tokens,
  in_tokens,
  out_tokens,
  cache_tokens,
  sessions,
  avg_duration,
  timed_sessions,
  tool_calls,
  tool_errors,
  agent_turns,
  user_turns,
  multi_model_sessions,
  printf('$%.2f', total_spend)::text as total_spend_display,
  CASE WHEN total_tokens < 1000 THEN CAST(total_tokens AS VARCHAR) WHEN total_tokens < 1000000 THEN printf('%.1fK', total_tokens / 1000.0) WHEN total_tokens < 1000000000 THEN printf('%.1fM', total_tokens / 1000000.0) ELSE printf('%.1fB', total_tokens / 1000000000.0) END::text as total_tokens_display,
  (CASE WHEN in_tokens < 1000 THEN CAST(in_tokens AS VARCHAR) WHEN in_tokens < 1000000 THEN printf('%.1fK', in_tokens / 1000.0) WHEN in_tokens < 1000000000 THEN printf('%.1fM', in_tokens / 1000000.0) ELSE printf('%.1fB', in_tokens / 1000000000.0) END || ' in / ' ||
   CASE WHEN out_tokens < 1000 THEN CAST(out_tokens AS VARCHAR) WHEN out_tokens < 1000000 THEN printf('%.1fK', out_tokens / 1000.0) WHEN out_tokens < 1000000000 THEN printf('%.1fM', out_tokens / 1000000.0) ELSE printf('%.1fB', out_tokens / 1000000000.0) END || ' out / ' ||
   CASE WHEN cache_tokens < 1000 THEN CAST(cache_tokens AS VARCHAR) WHEN cache_tokens < 1000000 THEN printf('%.1fK', cache_tokens / 1000.0) WHEN cache_tokens < 1000000000 THEN printf('%.1fM', cache_tokens / 1000000.0) ELSE printf('%.1fB', cache_tokens / 1000000000.0) END || ' cache')::text as token_breakdown_display,
  CASE WHEN sessions = 0 THEN '0%' ELSE printf('%.1f%%', multi_model_sessions * 100.0 / sessions) END::text as multi_model_sessions_pct,
  CASE WHEN avg_duration <= 0 THEN '-' WHEN avg_duration < 60 THEN CAST(avg_duration AS VARCHAR) || 's' WHEN avg_duration < 3600 THEN CAST(CAST(floor(avg_duration / 60) AS BIGINT) AS VARCHAR) || 'm ' || CAST(avg_duration % 60 AS VARCHAR) || 's' ELSE CAST(CAST(floor(avg_duration / 3600) AS BIGINT) AS VARCHAR) || 'h ' || CAST(CAST(floor((avg_duration % 3600) / 60) AS BIGINT) AS VARCHAR) || 'm' END::text as avg_duration_display,
  CASE WHEN tool_calls < 1000 THEN CAST(tool_calls AS VARCHAR) WHEN tool_calls < 1000000 THEN printf('%.1fK', tool_calls / 1000.0) WHEN tool_calls < 1000000000 THEN printf('%.1fM', tool_calls / 1000000.0) ELSE printf('%.1fB', tool_calls / 1000000000.0) END::text as tool_calls_display,
  CASE WHEN tool_errors < 1000 THEN CAST(tool_errors AS VARCHAR) WHEN tool_errors < 1000000 THEN printf('%.1fK', tool_errors / 1000.0) WHEN tool_errors < 1000000000 THEN printf('%.1fM', tool_errors / 1000000.0) ELSE printf('%.1fB', tool_errors / 1000000000.0) END::text as tool_errors_display,
  CASE WHEN tool_calls = 0 THEN '0%' ELSE printf('%.1f%%', tool_errors * 100.0 / tool_calls) END::text as tool_error_pct,
  CASE WHEN sessions = 0 THEN '$0.00' ELSE printf('$%.2f', total_spend / sessions) END::text as avg_cost_per_session_display,
  total_turns,
  CASE WHEN avg_tokens_per_turn < 1000 THEN CAST(avg_tokens_per_turn AS VARCHAR) WHEN avg_tokens_per_turn < 1000000 THEN printf('%.1fK', avg_tokens_per_turn / 1000.0) WHEN avg_tokens_per_turn < 1000000000 THEN printf('%.1fM', avg_tokens_per_turn / 1000000.0) ELSE printf('%.1fB', avg_tokens_per_turn / 1000000000.0) END::text as avg_tokens_per_turn_display,
  CASE WHEN sessions = 0 THEN '0' ELSE printf('%.1f', tool_calls * 1.0 / sessions) END::text as avg_tools_per_session_display
FROM derived
`

type GetSummaryParams struct {
	Days     int32
	Project  string
	Filename string
	Harness  string
	Provider string
	Model    string
	Tool     string
}

type GetSummaryRow struct {
	TotalSpend                float64
	TotalTokens               int64
	InTokens                  int64
	OutTokens                 int64
	CacheTokens               int64
	Sessions                  int64
	AvgDuration               int64
	TimedSessions             int64
	ToolCalls                 int64
	ToolErrors                int64
	AgentTurns                int64
	UserTurns                 int64
	MultiModelSessions        int64
	TotalSpendDisplay         string
	TotalTokensDisplay        string
	TokenBreakdownDisplay     string
	MultiModelSessionsPct     string
	AvgDurationDisplay        string
	ToolCallsDisplay          string
	ToolErrorsDisplay         string
	ToolErrorPct              string
	AvgCostPerSessionDisplay  string
	TotalTurns                int64
	AvgTokensPerTurnDisplay   string
	AvgToolsPerSessionDisplay string
}

func (q *Queries) GetSummary(ctx context.Context, arg GetSummaryParams) (GetSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getSummary,
		arg.Days,
		arg.Project,
		arg.Filename,
		arg.Harness,
		arg.Provider,
		arg.Model,
		arg.Tool,
	)
	var i GetSummaryRow
	err := row.Scan(
		&i.TotalSpend,
		&i.TotalTokens,
		&i.InTokens,
		&i.OutTokens,
		&i.CacheTokens,
		&i.Sessions,
		&i.AvgDuration,
		&i.TimedSessions,
		&i.ToolCalls,
		&i.ToolErrors,
		&i.AgentTurns,
		&i.UserTurns,
		&i.MultiModelSessions,
		&i.TotalSpendDisplay,
		&i.TotalTokensDisplay,
		&i.TokenBreakdownDisplay,
		&i.MultiModelSessionsPct,
		&i.AvgDurationDisplay,
		&i.ToolCallsDisplay,
		&i.ToolErrorsDisplay,
		&i.ToolErrorPct,
		&i.AvgCostPerSessionDisplay,
		&i.TotalTurns,
		&i.AvgTokensPerTurnDisplay,
		&i.AvgToolsPerSessionDisplay,
	)
	return i, err
}
