// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_profanity_models.sql

package db

import (
	"context"
	"database/sql"
)

const getProfanityModels = `-- name: GetProfanityModels :many
WITH filtered_hits AS (
  SELECT h.hit_id, h.harness, h.filename, h.project, h.ts, h.word, h.group_name, h.severity, h.model, h.provider
  FROM t_profanity_hits_attributed h
  JOIN t_sessions s ON s.harness = h.harness AND s.filename = h.filename
  WHERE h.model IS NOT NULL AND h.model != ''
    AND ($1::int = 0 OR epoch_ms(s.start_time) >= current_date - to_days($1::int))
    AND ($2::text = '' OR s.project = $2)
    AND ($3::text = '' OR s.filename = $3)
    AND ($4::text = '' OR h.harness = $4)
    AND ($5::text = '' OR h.provider = $5)
    AND ($6::text = '' OR h.model = $6)
    AND ($7::text = '' OR EXISTS (SELECT 1 FROM t_model_tools mt WHERE mt.harness = h.harness AND mt.filename = h.filename AND mt.tool = $7))
)
SELECT model, COALESCE(provider, 'unknown')::text as provider, COUNT(*)::bigint as count, COUNT(DISTINCT harness || ':' || filename)::bigint as sessions
FROM filtered_hits
GROUP BY model, provider
ORDER BY count DESC, model
LIMIT 20
`

type GetProfanityModelsParams struct {
	Days     int32
	Project  string
	Filename string
	Harness  string
	Provider string
	Model    string
	Tool     string
}

type GetProfanityModelsRow struct {
	Model    sql.NullString
	Provider string
	Count    int64
	Sessions int64
}

func (q *Queries) GetProfanityModels(ctx context.Context, arg GetProfanityModelsParams) ([]GetProfanityModelsRow, error) {
	rows, err := q.db.QueryContext(ctx, getProfanityModels,
		arg.Days,
		arg.Project,
		arg.Filename,
		arg.Harness,
		arg.Provider,
		arg.Model,
		arg.Tool,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProfanityModelsRow
	for rows.Next() {
		var i GetProfanityModelsRow
		if err := rows.Scan(
			&i.Model,
			&i.Provider,
			&i.Count,
			&i.Sessions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
