// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_harnesses.sql

package db

import (
	"context"
)

const getHarnesses = `-- name: GetHarnesses :many
WITH agg AS (
  SELECT sms.harness, COALESCE(SUM(sms.cost), 0)::float8 as spend, COALESCE(SUM(sms.in_tok+sms.out_tok+sms.cache_tok), 0)::bigint as tokens, COALESCE(SUM(sms.turns), 0)::bigint as turns, COALESCE(SUM(sms.tools), 0)::bigint as tools, COALESCE(SUM(sms.errors), 0)::bigint as errors
  FROM t_session_model_stats_raw sms
  WHERE ($4::int = 0 OR EXISTS (SELECT 1 FROM t_sessions s WHERE s.harness = sms.harness AND s.filename = sms.filename AND epoch_ms(s.start_time) >= current_date - to_days($4::int)))
    AND ($5::text = '' OR EXISTS (SELECT 1 FROM t_sessions s WHERE s.harness = sms.harness AND s.filename = sms.filename AND s.project = $5))
    AND ($6::text = '' OR sms.filename = $6)
    AND ($7::text = '' OR sms.harness = $7)
    AND ($8::text = '' OR sms.provider = $8)
    AND ($9::text = '' OR sms.model = $9)
    AND ($10::text = '' OR EXISTS (SELECT 1 FROM t_unified_events e WHERE e.harness = sms.harness AND e.filename = sms.filename AND e.tool = $10))
  GROUP BY sms.harness
)
SELECT
  harness,
  spend,
  printf('$%.4f', spend)::text as spend_display,
  tokens,
  CASE WHEN tokens < 1000 THEN CAST(tokens AS VARCHAR) WHEN tokens < 1000000 THEN printf('%.1fK', tokens / 1000.0) WHEN tokens < 1000000000 THEN printf('%.1fM', tokens / 1000000.0) ELSE printf('%.1fB', tokens / 1000000000.0) END::text as tokens_display,
  turns,
  tools,
  errors
FROM agg
ORDER BY
  CASE WHEN $1::text = 'harnesses' AND $2::text = 'harness' AND $3::text = 'asc' THEN harness END ASC,
  CASE WHEN $1::text = 'harnesses' AND $2::text = 'harness' AND $3::text = 'desc' THEN harness END DESC,
  CASE WHEN $1::text = 'harnesses' AND $2::text = 'spend' AND $3::text = 'asc' THEN spend END ASC,
  CASE WHEN $1::text = 'harnesses' AND $2::text = 'spend' AND $3::text = 'desc' THEN spend END DESC,
  CASE WHEN $1::text = 'harnesses' AND $2::text = 'tokens' AND $3::text = 'asc' THEN tokens END ASC,
  CASE WHEN $1::text = 'harnesses' AND $2::text = 'tokens' AND $3::text = 'desc' THEN tokens END DESC,
  CASE WHEN $1::text = 'harnesses' AND $2::text = 'turns' AND $3::text = 'asc' THEN turns END ASC,
  CASE WHEN $1::text = 'harnesses' AND $2::text = 'turns' AND $3::text = 'desc' THEN turns END DESC,
  CASE WHEN $1::text = 'harnesses' AND $2::text = 'tools' AND $3::text = 'asc' THEN tools END ASC,
  CASE WHEN $1::text = 'harnesses' AND $2::text = 'tools' AND $3::text = 'desc' THEN tools END DESC,
  spend DESC
`

type GetHarnessesParams struct {
	SortTable string
	SortBy    string
	SortDir   string
	Days      int32
	Project   string
	Filename  string
	Harness   string
	Provider  string
	Model     string
	Tool      string
}

type GetHarnessesRow struct {
	Harness       string
	Spend         float64
	SpendDisplay  string
	Tokens        int64
	TokensDisplay string
	Turns         int64
	Tools         int64
	Errors        int64
}

func (q *Queries) GetHarnesses(ctx context.Context, arg GetHarnessesParams) ([]GetHarnessesRow, error) {
	rows, err := q.db.QueryContext(ctx, getHarnesses,
		arg.SortTable,
		arg.SortBy,
		arg.SortDir,
		arg.Days,
		arg.Project,
		arg.Filename,
		arg.Harness,
		arg.Provider,
		arg.Model,
		arg.Tool,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHarnessesRow
	for rows.Next() {
		var i GetHarnessesRow
		if err := rows.Scan(
			&i.Harness,
			&i.Spend,
			&i.SpendDisplay,
			&i.Tokens,
			&i.TokensDisplay,
			&i.Turns,
			&i.Tools,
			&i.Errors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
