// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_session_profanity.sql

package db

import (
	"context"
)

const getSessionProfanity = `-- name: GetSessionProfanity :many
WITH filtered AS (
  SELECT h.hit_id, h.harness, h.filename, h.project, h.ts, h.word, h.group_name, h.severity, h.model, h.provider
  FROM t_profanity_hits_attributed h
  WHERE h.harness = $1
    AND h.filename = $2
),
agg AS (
  SELECT
    group_name,
    any_value(severity)::text as severity,
    COUNT(*)::bigint as count,
    COUNT(*) FILTER (WHERE severity = 'strong')::bigint as strong_count,
    COUNT(*) FILTER (WHERE severity = 'moderate')::bigint as moderate_count,
    COUNT(*) FILTER (WHERE severity = 'mild')::bigint as mild_count,
    string_agg(DISTINCT word, ', ' ORDER BY word)::text as words
  FROM filtered
  GROUP BY group_name
),
scored AS (
  SELECT
    group_name,
    severity,
    count,
    strong_count,
    moderate_count,
    mild_count,
    words,
    SUM(count) OVER ()::bigint as total_hits,
    SUM((CASE severity WHEN 'strong' THEN 3 WHEN 'moderate' THEN 2 ELSE 1 END) * count) OVER ()::bigint as feel_score
  FROM agg
)
SELECT
  group_name,
  severity,
  count,
  strong_count,
  moderate_count,
  mild_count,
  words,
  total_hits,
  feel_score,
  CASE
    WHEN feel_score = 0 THEN 'calm'
    WHEN feel_score <= 3 THEN 'irked'
    WHEN feel_score <= 9 THEN 'frustrated'
    ELSE 'furious'
  END::text as feel_display
FROM scored
ORDER BY count DESC, group_name
LIMIT 20
`

type GetSessionProfanityParams struct {
	Harness  string
	Filename string
}

type GetSessionProfanityRow struct {
	GroupName     string
	Severity      string
	Count         int64
	StrongCount   int64
	ModerateCount int64
	MildCount     int64
	Words         string
	TotalHits     int64
	FeelScore     int64
	FeelDisplay   string
}

func (q *Queries) GetSessionProfanity(ctx context.Context, arg GetSessionProfanityParams) ([]GetSessionProfanityRow, error) {
	rows, err := q.db.QueryContext(ctx, getSessionProfanity, arg.Harness, arg.Filename)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSessionProfanityRow
	for rows.Next() {
		var i GetSessionProfanityRow
		if err := rows.Scan(
			&i.GroupName,
			&i.Severity,
			&i.Count,
			&i.StrongCount,
			&i.ModerateCount,
			&i.MildCount,
			&i.Words,
			&i.TotalHits,
			&i.FeelScore,
			&i.FeelDisplay,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
