// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_sessions.sql

package db

import (
	"context"
	"database/sql"
)

const getSessions = `-- name: GetSessions :many
WITH base AS (
  SELECT 
    harness,
    filename,
    strftime(to_timestamp(start_time/1000)::TIMESTAMP, '%Y-%m-%dT%H:%M:%S.%f')::text as start_time_str,
    strftime(to_timestamp(end_time/1000)::TIMESTAMP, '%Y-%m-%dT%H:%M:%S.%f')::text as end_time_str,
    date_diff('second', to_timestamp(start_time/1000)::TIMESTAMP, to_timestamp(end_time/1000)::TIMESTAMP)::bigint as duration_sec_calc,
    project,
    cwd,
    cost,
    in_tok,
    out_tok,
    cache_tok,
    (in_tok + out_tok + cache_tok)::bigint as total_tokens,
    user_turns,
    agent_turns,
    (user_turns + agent_turns)::bigint as total_turns,
    errors,
    tool_count,
    tool_error_count,
    tool_breakdown::text as tool_breakdown_json,
    tool_error_breakdown::text as tool_error_breakdown_json,
    model_tool_breakdown::text as model_tool_breakdown_json,
    model_stats::text as model_stats_json,
    COALESCE(to_json(models)::text, '[]')::text as models_json,
    start_time,
    end_time,
    duration_sec
  FROM t_sessions s
  WHERE ($4::int = 0 OR epoch_ms(start_time) >= current_date - to_days($4::int))
    AND ($5::text = '' OR project = $5)
    AND ($6::text = '' OR filename = $6)
    AND ($7::text = '' OR harness = $7)
    AND ($8::text = '' OR EXISTS (SELECT 1 FROM t_session_model_stats_raw sms WHERE sms.harness = s.harness AND sms.filename = s.filename AND sms.provider = $8))
    AND ($9::text = '' OR EXISTS (SELECT 1 FROM t_session_model_stats_raw sms WHERE sms.harness = s.harness AND sms.filename = s.filename AND sms.model = $9))
    AND ($10::text = '' OR EXISTS (SELECT 1 FROM t_unified_events e WHERE e.harness = s.harness AND e.filename = s.filename AND e.tool = $10))
)
SELECT
  harness,
  filename,
  start_time_str,
  end_time_str,
  duration_sec_calc,
  project,
  cwd,
  cost,
  in_tok,
  out_tok,
  cache_tok,
  total_tokens,
  user_turns,
  agent_turns,
  total_turns,
  errors,
  tool_count,
  tool_error_count,
  tool_breakdown_json,
  tool_error_breakdown_json,
  model_tool_breakdown_json,
  model_stats_json,
  models_json,
  printf('$%.4f', cost)::text as cost_display,
  CASE WHEN total_tokens < 1000 THEN CAST(total_tokens AS VARCHAR) WHEN total_tokens < 1000000 THEN printf('%.1fK', total_tokens / 1000.0) WHEN total_tokens < 1000000000 THEN printf('%.1fM', total_tokens / 1000000.0) ELSE printf('%.1fB', total_tokens / 1000000000.0) END::text as total_tokens_display,
  (CASE WHEN in_tok < 1000 THEN CAST(in_tok AS VARCHAR) WHEN in_tok < 1000000 THEN printf('%.1fK', in_tok / 1000.0) WHEN in_tok < 1000000000 THEN printf('%.1fM', in_tok / 1000000.0) ELSE printf('%.1fB', in_tok / 1000000000.0) END || ' in / ' ||
   CASE WHEN out_tok < 1000 THEN CAST(out_tok AS VARCHAR) WHEN out_tok < 1000000 THEN printf('%.1fK', out_tok / 1000.0) WHEN out_tok < 1000000000 THEN printf('%.1fM', out_tok / 1000000.0) ELSE printf('%.1fB', out_tok / 1000000000.0) END || ' out / ' ||
   CASE WHEN cache_tok < 1000 THEN CAST(cache_tok AS VARCHAR) WHEN cache_tok < 1000000 THEN printf('%.1fK', cache_tok / 1000.0) WHEN cache_tok < 1000000000 THEN printf('%.1fM', cache_tok / 1000000.0) ELSE printf('%.1fB', cache_tok / 1000000000.0) END || ' cache')::text as token_breakdown_display,
  CASE WHEN duration_sec_calc <= 0 THEN '-' WHEN duration_sec_calc < 60 THEN CAST(duration_sec_calc AS VARCHAR) || 's' WHEN duration_sec_calc < 3600 THEN CAST(CAST(floor(duration_sec_calc / 60) AS BIGINT) AS VARCHAR) || 'm ' || CAST(duration_sec_calc % 60 AS VARCHAR) || 's' ELSE CAST(CAST(floor(duration_sec_calc / 3600) AS BIGINT) AS VARCHAR) || 'h ' || CAST(CAST(floor((duration_sec_calc % 3600) / 60) AS BIGINT) AS VARCHAR) || 'm' END::text as duration_display,
  CASE WHEN tool_count = 0 THEN '0%' ELSE printf('%.1f%%', tool_error_count * 100.0 / tool_count) END::text as tool_error_pct
FROM base
ORDER BY
  CASE WHEN $1::text = 'sessions' AND $2::text = 'when' AND $3::text = 'asc' THEN start_time END ASC,
  CASE WHEN $1::text = 'sessions' AND $2::text = 'when' AND $3::text = 'desc' THEN start_time END DESC,
  CASE WHEN $1::text = 'sessions' AND $2::text = 'project' AND $3::text = 'asc' THEN project END ASC,
  CASE WHEN $1::text = 'sessions' AND $2::text = 'project' AND $3::text = 'desc' THEN project END DESC,
  CASE WHEN $1::text = 'sessions' AND $2::text = 'spend' AND $3::text = 'asc' THEN cost END ASC,
  CASE WHEN $1::text = 'sessions' AND $2::text = 'spend' AND $3::text = 'desc' THEN cost END DESC,
  CASE WHEN $1::text = 'sessions' AND $2::text = 'tokens' AND $3::text = 'asc' THEN in_tok + out_tok + cache_tok END ASC,
  CASE WHEN $1::text = 'sessions' AND $2::text = 'tokens' AND $3::text = 'desc' THEN in_tok + out_tok + cache_tok END DESC,
  CASE WHEN $1::text = 'sessions' AND $2::text = 'duration' AND $3::text = 'asc' THEN duration_sec END ASC,
  CASE WHEN $1::text = 'sessions' AND $2::text = 'duration' AND $3::text = 'desc' THEN duration_sec END DESC,
  CASE WHEN $1::text = 'sessions' AND $2::text = 'turns' AND $3::text = 'asc' THEN agent_turns END ASC,
  CASE WHEN $1::text = 'sessions' AND $2::text = 'turns' AND $3::text = 'desc' THEN agent_turns END DESC,
  start_time DESC
LIMIT 100
`

type GetSessionsParams struct {
	SortTable string
	SortBy    string
	SortDir   string
	Days      int32
	Project   string
	Filename  string
	Harness   string
	Provider  string
	Model     string
	Tool      string
}

type GetSessionsRow struct {
	Harness                string
	Filename               string
	StartTimeStr           string
	EndTimeStr             string
	DurationSecCalc        int64
	Project                sql.NullString
	Cwd                    sql.NullString
	Cost                   float64
	InTok                  int64
	OutTok                 int64
	CacheTok               int64
	TotalTokens            int64
	UserTurns              int64
	AgentTurns             int64
	TotalTurns             int64
	Errors                 int64
	ToolCount              int64
	ToolErrorCount         int64
	ToolBreakdownJson      string
	ToolErrorBreakdownJson string
	ModelToolBreakdownJson string
	ModelStatsJson         string
	ModelsJson             string
	CostDisplay            string
	TotalTokensDisplay     string
	TokenBreakdownDisplay  string
	DurationDisplay        string
	ToolErrorPct           string
}

func (q *Queries) GetSessions(ctx context.Context, arg GetSessionsParams) ([]GetSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSessions,
		arg.SortTable,
		arg.SortBy,
		arg.SortDir,
		arg.Days,
		arg.Project,
		arg.Filename,
		arg.Harness,
		arg.Provider,
		arg.Model,
		arg.Tool,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSessionsRow
	for rows.Next() {
		var i GetSessionsRow
		if err := rows.Scan(
			&i.Harness,
			&i.Filename,
			&i.StartTimeStr,
			&i.EndTimeStr,
			&i.DurationSecCalc,
			&i.Project,
			&i.Cwd,
			&i.Cost,
			&i.InTok,
			&i.OutTok,
			&i.CacheTok,
			&i.TotalTokens,
			&i.UserTurns,
			&i.AgentTurns,
			&i.TotalTurns,
			&i.Errors,
			&i.ToolCount,
			&i.ToolErrorCount,
			&i.ToolBreakdownJson,
			&i.ToolErrorBreakdownJson,
			&i.ModelToolBreakdownJson,
			&i.ModelStatsJson,
			&i.ModelsJson,
			&i.CostDisplay,
			&i.TotalTokensDisplay,
			&i.TokenBreakdownDisplay,
			&i.DurationDisplay,
			&i.ToolErrorPct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
