// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_providers.sql

package db

import (
	"context"
	"database/sql"
)

const getProviders = `-- name: GetProviders :many
WITH agg AS (
  SELECT sms.provider, COALESCE(SUM(sms.cost), 0)::float8 as spend, COALESCE(SUM(sms.in_tok+sms.out_tok+sms.cache_tok), 0)::bigint as tokens, COALESCE(SUM(sms.tools), 0)::bigint as tools, COALESCE(SUM(sms.errors), 0)::bigint as errors
  FROM t_session_model_stats_raw sms
  WHERE ($4::int = 0 OR EXISTS (SELECT 1 FROM t_sessions s WHERE s.harness = sms.harness AND s.filename = sms.filename AND epoch_ms(s.start_time) >= current_date - to_days($4::int)))
    AND ($5::text = '' OR EXISTS (SELECT 1 FROM t_sessions s WHERE s.harness = sms.harness AND s.filename = sms.filename AND s.project = $5))
    AND ($6::text = '' OR sms.filename = $6)
    AND ($7::text = '' OR sms.harness = $7)
    AND ($8::text = '' OR sms.provider = $8)
    AND ($9::text = '' OR sms.model = $9)
    AND ($10::text = '' OR EXISTS (SELECT 1 FROM t_unified_events e WHERE e.harness = sms.harness AND e.filename = sms.filename AND e.tool = $10))
  GROUP BY sms.provider
)
SELECT
  provider,
  spend,
  printf('$%.4f', spend)::text as spend_display,
  tokens,
  CASE WHEN tokens < 1000 THEN CAST(tokens AS VARCHAR) WHEN tokens < 1000000 THEN printf('%.1fK', tokens / 1000.0) WHEN tokens < 1000000000 THEN printf('%.1fM', tokens / 1000000.0) ELSE printf('%.1fB', tokens / 1000000000.0) END::text as tokens_display,
  tools,
  errors
FROM agg
ORDER BY
  CASE WHEN $1::text = 'providers' AND $2::text = 'provider' AND $3::text = 'asc' THEN provider END ASC,
  CASE WHEN $1::text = 'providers' AND $2::text = 'provider' AND $3::text = 'desc' THEN provider END DESC,
  CASE WHEN $1::text = 'providers' AND $2::text = 'spend' AND $3::text = 'asc' THEN spend END ASC,
  CASE WHEN $1::text = 'providers' AND $2::text = 'spend' AND $3::text = 'desc' THEN spend END DESC,
  CASE WHEN $1::text = 'providers' AND $2::text = 'tokens' AND $3::text = 'asc' THEN tokens END ASC,
  CASE WHEN $1::text = 'providers' AND $2::text = 'tokens' AND $3::text = 'desc' THEN tokens END DESC,
  CASE WHEN $1::text = 'providers' AND $2::text = 'tools' AND $3::text = 'asc' THEN tools END ASC,
  CASE WHEN $1::text = 'providers' AND $2::text = 'tools' AND $3::text = 'desc' THEN tools END DESC,
  spend DESC
`

type GetProvidersParams struct {
	SortTable string
	SortBy    string
	SortDir   string
	Days      int32
	Project   string
	Filename  string
	Harness   string
	Provider  string
	Model     string
	Tool      string
}

type GetProvidersRow struct {
	Provider      sql.NullString
	Spend         float64
	SpendDisplay  string
	Tokens        int64
	TokensDisplay string
	Tools         int64
	Errors        int64
}

func (q *Queries) GetProviders(ctx context.Context, arg GetProvidersParams) ([]GetProvidersRow, error) {
	rows, err := q.db.QueryContext(ctx, getProviders,
		arg.SortTable,
		arg.SortBy,
		arg.SortDir,
		arg.Days,
		arg.Project,
		arg.Filename,
		arg.Harness,
		arg.Provider,
		arg.Model,
		arg.Tool,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProvidersRow
	for rows.Next() {
		var i GetProvidersRow
		if err := rows.Scan(
			&i.Provider,
			&i.Spend,
			&i.SpendDisplay,
			&i.Tokens,
			&i.TokensDisplay,
			&i.Tools,
			&i.Errors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
