// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_tools.sql

package db

import (
	"context"
	"database/sql"
)

const getTools = `-- name: GetTools :many
WITH agg AS (
  SELECT mt.tool, COALESCE(SUM(mt.count), 0)::bigint as count, COALESCE(SUM(mt.errors), 0)::bigint as errors
  FROM t_model_tools mt
  WHERE mt.tool IS NOT NULL
    AND ($4::int = 0 OR EXISTS (SELECT 1 FROM t_sessions s WHERE s.harness = mt.harness AND s.filename = mt.filename AND epoch_ms(s.start_time) >= current_date - to_days($4::int)))
    AND ($5::text = '' OR EXISTS (SELECT 1 FROM t_sessions s WHERE s.harness = mt.harness AND s.filename = mt.filename AND s.project = $5))
    AND ($6::text = '' OR mt.filename = $6)
    AND ($7::text = '' OR mt.harness = $7)
    AND ($8::text = '' OR mt.provider = $8)
    AND ($9::text = '' OR mt.model = $9)
    AND ($10::text = '' OR mt.tool = $10)
  GROUP BY mt.tool
)
SELECT tool, count, errors, CASE WHEN count = 0 THEN '0%' ELSE printf('%.1f%%', errors * 100.0 / count) END::text as error_pct FROM agg
ORDER BY
  CASE WHEN $1::text = 'tools' AND $2::text = 'tool' AND $3::text = 'asc' THEN tool END ASC,
  CASE WHEN $1::text = 'tools' AND $2::text = 'tool' AND $3::text = 'desc' THEN tool END DESC,
  CASE WHEN $1::text = 'tools' AND $2::text = 'count' AND $3::text = 'asc' THEN count END ASC,
  CASE WHEN $1::text = 'tools' AND $2::text = 'count' AND $3::text = 'desc' THEN count END DESC,
  CASE WHEN $1::text = 'tools' AND $2::text = 'errors' AND $3::text = 'asc' THEN errors END ASC,
  CASE WHEN $1::text = 'tools' AND $2::text = 'errors' AND $3::text = 'desc' THEN errors END DESC,
  count DESC
`

type GetToolsParams struct {
	SortTable string
	SortBy    string
	SortDir   string
	Days      int32
	Project   string
	Filename  string
	Harness   string
	Provider  string
	Model     string
	Tool      string
}

type GetToolsRow struct {
	Tool     sql.NullString
	Count    int64
	Errors   int64
	ErrorPct string
}

func (q *Queries) GetTools(ctx context.Context, arg GetToolsParams) ([]GetToolsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTools,
		arg.SortTable,
		arg.SortBy,
		arg.SortDir,
		arg.Days,
		arg.Project,
		arg.Filename,
		arg.Harness,
		arg.Provider,
		arg.Model,
		arg.Tool,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetToolsRow
	for rows.Next() {
		var i GetToolsRow
		if err := rows.Scan(
			&i.Tool,
			&i.Count,
			&i.Errors,
			&i.ErrorPct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
