// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_models.sql

package db

import (
	"context"
	"database/sql"
)

const getModels = `-- name: GetModels :many
WITH filtered AS (
  SELECT sms.harness, sms.filename, sms.raw_model, sms.model, sms.provider, sms.turns, sms.cost, sms.in_tok, sms.out_tok, sms.cache_tok, sms.tools, sms.errors
  FROM t_session_model_stats_raw sms
  WHERE sms.model IS NOT NULL AND sms.model != ''
    AND ($4::int = 0 OR EXISTS (SELECT 1 FROM t_sessions s WHERE s.harness = sms.harness AND s.filename = sms.filename AND epoch_ms(s.start_time) >= current_date - to_days($4::int)))
    AND ($5::text = '' OR EXISTS (SELECT 1 FROM t_sessions s WHERE s.harness = sms.harness AND s.filename = sms.filename AND s.project = $5))
    AND ($6::text = '' OR sms.filename = $6)
    AND ($7::text = '' OR sms.harness = $7)
    AND ($8::text = '' OR sms.provider = $8)
    AND ($9::text = '' OR sms.model = $9)
    AND ($10::text = '' OR EXISTS (
      SELECT 1
      FROM t_model_tools mt
      WHERE mt.harness = sms.harness
        AND mt.filename = sms.filename
        AND mt.model = sms.model
        AND mt.provider = sms.provider
        AND mt.tool = $10
    ))
),
agg AS (
  SELECT
    sms.model,
    COALESCE(sms.provider, 'unknown')::text as provider,
    COALESCE(SUM(sms.cost), 0)::float8 as spend,
    COUNT(DISTINCT sms.harness || ':' || sms.filename)::bigint as sessions,
    CASE
      WHEN COUNT(DISTINCT sms.harness || ':' || sms.filename) = 0 THEN 0
      ELSE (COALESCE(SUM(sms.cost), 0) / COUNT(DISTINCT sms.harness || ':' || sms.filename))::float8
    END as avg_cost_per_session,
    COALESCE(SUM(sms.in_tok+sms.out_tok+sms.cache_tok), 0)::bigint as tokens,
    COALESCE(SUM(CASE WHEN sms.cost = 0 AND (sms.in_tok + sms.out_tok + sms.cache_tok) > 0 THEN sms.in_tok + sms.out_tok + sms.cache_tok ELSE 0 END), 0)::bigint as unpriced_tokens,
    COUNT(DISTINCT CASE WHEN sms.cost = 0 AND (sms.in_tok + sms.out_tok + sms.cache_tok) > 0 THEN sms.harness || ':' || sms.filename ELSE NULL END)::bigint as unpriced_sessions,
    COALESCE(SUM(sms.tools), 0)::bigint as tools,
    COALESCE(SUM(sms.errors), 0)::bigint as errors
  FROM filtered sms
  GROUP BY sms.model, sms.provider
)
SELECT
  model,
  provider,
  spend,
  printf('$%.4f', spend)::text as spend_display,
  sessions,
  avg_cost_per_session,
  printf('$%.4f', avg_cost_per_session)::text as avg_cost_per_session_display,
  tokens,
  CASE WHEN tokens < 1000 THEN CAST(tokens AS VARCHAR) WHEN tokens < 1000000 THEN printf('%.1fK', tokens / 1000.0) WHEN tokens < 1000000000 THEN printf('%.1fM', tokens / 1000000.0) ELSE printf('%.1fB', tokens / 1000000000.0) END::text as tokens_display,
  unpriced_tokens,
  CASE WHEN unpriced_tokens < 1000 THEN CAST(unpriced_tokens AS VARCHAR) WHEN unpriced_tokens < 1000000 THEN printf('%.1fK', unpriced_tokens / 1000.0) WHEN unpriced_tokens < 1000000000 THEN printf('%.1fM', unpriced_tokens / 1000000.0) ELSE printf('%.1fB', unpriced_tokens / 1000000000.0) END::text as unpriced_tokens_display,
  unpriced_sessions,
  tools,
  errors
FROM agg
ORDER BY
  CASE WHEN $1::text = 'models' AND $2::text = 'model' AND $3::text = 'asc' THEN model END ASC,
  CASE WHEN $1::text = 'models' AND $2::text = 'model' AND $3::text = 'desc' THEN model END DESC,
  CASE WHEN $1::text = 'models' AND $2::text = 'provider' AND $3::text = 'asc' THEN provider END ASC,
  CASE WHEN $1::text = 'models' AND $2::text = 'provider' AND $3::text = 'desc' THEN provider END DESC,
  CASE WHEN $1::text = 'models' AND $2::text = 'spend' AND $3::text = 'asc' THEN spend END ASC,
  CASE WHEN $1::text = 'models' AND $2::text = 'spend' AND $3::text = 'desc' THEN spend END DESC,
  CASE WHEN $1::text = 'models' AND $2::text = 'avg_cost' AND $3::text = 'asc' THEN avg_cost_per_session END ASC,
  CASE WHEN $1::text = 'models' AND $2::text = 'avg_cost' AND $3::text = 'desc' THEN avg_cost_per_session END DESC,
  CASE WHEN $1::text = 'models' AND $2::text = 'tokens' AND $3::text = 'asc' THEN tokens END ASC,
  CASE WHEN $1::text = 'models' AND $2::text = 'tokens' AND $3::text = 'desc' THEN tokens END DESC,
  CASE WHEN $1::text = 'models' AND $2::text = 'tools' AND $3::text = 'asc' THEN tools END ASC,
  CASE WHEN $1::text = 'models' AND $2::text = 'tools' AND $3::text = 'desc' THEN tools END DESC,
  tokens DESC
`

type GetModelsParams struct {
	SortTable string
	SortBy    string
	SortDir   string
	Days      int32
	Project   string
	Filename  string
	Harness   string
	Provider  string
	Model     string
	Tool      string
}

type GetModelsRow struct {
	Model                    sql.NullString
	Provider                 string
	Spend                    float64
	SpendDisplay             string
	Sessions                 int64
	AvgCostPerSession        float64
	AvgCostPerSessionDisplay string
	Tokens                   int64
	TokensDisplay            string
	UnpricedTokens           int64
	UnpricedTokensDisplay    string
	UnpricedSessions         int64
	Tools                    int64
	Errors                   int64
}

func (q *Queries) GetModels(ctx context.Context, arg GetModelsParams) ([]GetModelsRow, error) {
	rows, err := q.db.QueryContext(ctx, getModels,
		arg.SortTable,
		arg.SortBy,
		arg.SortDir,
		arg.Days,
		arg.Project,
		arg.Filename,
		arg.Harness,
		arg.Provider,
		arg.Model,
		arg.Tool,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetModelsRow
	for rows.Next() {
		var i GetModelsRow
		if err := rows.Scan(
			&i.Model,
			&i.Provider,
			&i.Spend,
			&i.SpendDisplay,
			&i.Sessions,
			&i.AvgCostPerSession,
			&i.AvgCostPerSessionDisplay,
			&i.Tokens,
			&i.TokensDisplay,
			&i.UnpricedTokens,
			&i.UnpricedTokensDisplay,
			&i.UnpricedSessions,
			&i.Tools,
			&i.Errors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
