// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_projects.sql

package db

import (
	"context"
	"database/sql"
)

const getProjects = `-- name: GetProjects :many
WITH agg AS (
  SELECT s.project, COALESCE(SUM(s.cost), 0)::float8 as spend, COUNT(*)::bigint as sessions, COALESCE(AVG(CASE WHEN s.duration_sec > 0 AND s.duration_sec < 86400 THEN s.duration_sec END), 0)::bigint as avg_duration
  FROM t_sessions s
  WHERE ($4::int = 0 OR epoch_ms(s.start_time) >= current_date - to_days($4::int))
    AND ($5::text = '' OR s.project = $5)
    AND ($6::text = '' OR s.filename = $6)
    AND ($7::text = '' OR EXISTS (SELECT 1 FROM t_unified_events e WHERE e.harness = $7 AND e.harness = s.harness AND e.filename = s.filename))
    AND ($8::text = '' OR EXISTS (SELECT 1 FROM t_session_model_stats_raw sms WHERE sms.harness = s.harness AND sms.filename = s.filename AND sms.provider = $8))
    AND ($9::text = '' OR EXISTS (SELECT 1 FROM t_session_model_stats_raw sms WHERE sms.harness = s.harness AND sms.filename = s.filename AND sms.model = $9))
    AND ($10::text = '' OR EXISTS (SELECT 1 FROM t_unified_events e WHERE e.harness = s.harness AND e.filename = s.filename AND e.tool = $10))
  GROUP BY s.project
)
SELECT
  project,
  spend,
  printf('$%.4f', spend)::text as spend_display,
  sessions,
  avg_duration,
  CASE WHEN avg_duration <= 0 THEN '-' WHEN avg_duration < 60 THEN CAST(avg_duration AS VARCHAR) || 's' WHEN avg_duration < 3600 THEN CAST(CAST(floor(avg_duration / 60) AS BIGINT) AS VARCHAR) || 'm ' || CAST(avg_duration % 60 AS VARCHAR) || 's' ELSE CAST(CAST(floor(avg_duration / 3600) AS BIGINT) AS VARCHAR) || 'h ' || CAST(CAST(floor((avg_duration % 3600) / 60) AS BIGINT) AS VARCHAR) || 'm' END::text as avg_duration_display
FROM agg
ORDER BY
  CASE WHEN $1::text = 'projects' AND $2::text = 'project' AND $3::text = 'asc' THEN project END ASC,
  CASE WHEN $1::text = 'projects' AND $2::text = 'project' AND $3::text = 'desc' THEN project END DESC,
  CASE WHEN $1::text = 'projects' AND $2::text = 'spend' AND $3::text = 'asc' THEN spend END ASC,
  CASE WHEN $1::text = 'projects' AND $2::text = 'spend' AND $3::text = 'desc' THEN spend END DESC,
  CASE WHEN $1::text = 'projects' AND $2::text = 'sessions' AND $3::text = 'asc' THEN sessions END ASC,
  CASE WHEN $1::text = 'projects' AND $2::text = 'sessions' AND $3::text = 'desc' THEN sessions END DESC,
  CASE WHEN $1::text = 'projects' AND $2::text = 'avg_duration' AND $3::text = 'asc' THEN avg_duration END ASC,
  CASE WHEN $1::text = 'projects' AND $2::text = 'avg_duration' AND $3::text = 'desc' THEN avg_duration END DESC,
  spend DESC
`

type GetProjectsParams struct {
	SortTable string
	SortBy    string
	SortDir   string
	Days      int32
	Project   string
	Filename  string
	Harness   string
	Provider  string
	Model     string
	Tool      string
}

type GetProjectsRow struct {
	Project            sql.NullString
	Spend              float64
	SpendDisplay       string
	Sessions           int64
	AvgDuration        int64
	AvgDurationDisplay string
}

func (q *Queries) GetProjects(ctx context.Context, arg GetProjectsParams) ([]GetProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, getProjects,
		arg.SortTable,
		arg.SortBy,
		arg.SortDir,
		arg.Days,
		arg.Project,
		arg.Filename,
		arg.Harness,
		arg.Provider,
		arg.Model,
		arg.Tool,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectsRow
	for rows.Next() {
		var i GetProjectsRow
		if err := rows.Scan(
			&i.Project,
			&i.Spend,
			&i.SpendDisplay,
			&i.Sessions,
			&i.AvgDuration,
			&i.AvgDurationDisplay,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
