// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

type ApiPricing struct {
	ModelKey       string
	Provider       string
	InputCost      float64
	OutputCost     float64
	CacheCost      float64
	CacheWriteCost sql.NullFloat64
}

type TModelTool struct {
	Harness  string
	Filename string
	Model    sql.NullString
	Provider sql.NullString
	Tool     sql.NullString
	Count    int64
	Errors   int64
}

type TProfanityHitsAttributed struct {
	HitID     int64
	Harness   string
	Filename  string
	Project   sql.NullString
	Ts        sql.NullInt64
	Word      string
	GroupName string
	Severity  string
	Model     sql.NullString
	Provider  sql.NullString
}

type TSession struct {
	Harness            string
	Filename           string
	StartTime          int64
	EndTime            int64
	DurationSec        int64
	Project            sql.NullString
	Cwd                sql.NullString
	Models             pqtype.NullRawMessage
	Cost               float64
	InTok              int64
	OutTok             int64
	CacheTok           int64
	UserTurns          int64
	AgentTurns         int64
	Errors             int64
	ToolCount          int64
	ToolErrorCount     int64
	ToolBreakdown      pqtype.NullRawMessage
	ToolErrorBreakdown pqtype.NullRawMessage
	ModelToolBreakdown pqtype.NullRawMessage
	ModelStats         pqtype.NullRawMessage
}

type TSessionModelStatsRaw struct {
	Harness  string
	Filename string
	RawModel sql.NullString
	Model    sql.NullString
	Provider sql.NullString
	Turns    int64
	Cost     float64
	InTok    int64
	OutTok   int64
	CacheTok int64
	Tools    int64
	Errors   int64
}

type TUnifiedEvent struct {
	Harness    string
	Filename   string
	Project    sql.NullString
	RawModel   sql.NullString
	Model      sql.NullString
	Provider   sql.NullString
	SessionCwd sql.NullString
	Ts         int64
	Cost       float64
	InTok      int64
	OutTok     int64
	CacheTok   int64
	IsTurn     int32
	IsUser     int32
	IsTool     int32
	IsError    int32
	Tool       sql.NullString
}
